// Code generated by Slice Machine. DO NOT EDIT.

import ContentWidth from "./ContentWidth/index.svelte";
import Hero from "./Hero/index.svelte";
import RichText from "./RichText/index.svelte";


export const components = {
  content_width_media: ContentWidth,
  hero: Hero,
  rich_text: RichText,
};
