// Code generated by Slice Machine. DO NOT EDIT.

import ContentWidthMedia from "./ContentWidthMedia/index.svelte";
import RichText from "./RichText/index.svelte";

export const components = {
  content_width_media: ContentWidthMedia,
  rich_text: RichText,
};
